version: '3.8'
services:

  backend:
    build:
      context: docker/nodejs
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    entrypoint: sh -c "cd /var/www && yarn && npm run start:dev"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www

  frontend:
    build:
      context: docker/nodejs
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    restart: always
    entrypoint: sh -c "cd /var/www && yarn && yarn dev"
    depends_on:
      - backend
    volumes:
      - ./frontend:/var/www

  nginx:
    build: docker/nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./:/www
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: mongo:4.4.6
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${DOCKER_DATABASE}"
      - "MONGO_INITDB_ROOT_USERNAME=${DOCKER_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DOCKER_PASSWORD}"
    volumes:
      - database:/data/db


volumes:
  database:

networks:
  default: